# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherActivity' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 5.2'
  target 'WeatherActivityWidgetExtension' do
    inherit! :search_paths
  end
  pod 'IQKeyboardManagerSwift'
  pod 'KeychainSwift', '~> 19.0'
  
  pod 'CHIPageControl/Aleppo'
  
  pod 'SkeletonView'
  pod 'DropDown'
  # Pods for WeatherActivity

  target 'WeatherActivityTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WeatherActivityUITests' do
    # Pods for testing
  end

end
